# Data Cleaning Practice 6

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = pd.read_csv('messy_data5.csv')

In [4]:
df = data.copy(deep=True)

#

# Basic inspection

In [6]:
df.shape

(200, 10)

In [7]:
df.head()

,Order_ID,Customer_Name,Email,City,Product,Quantity,Price,Customer_Rating,Order_Date,Payment_Method
0,1001,Ravi,NaN,Belagavi,Headphone,NaN,NaN,4.0,05/01/2025,Cash
1,1002,Amit,user1@gmail.com,Belgaum,Laptop,-1.0,500.0,1.0,06-01-2025,UPI
2,1003,Omkar,user2gmail.com,bangalore,Laptop,3.0,NaN,6.0,06-01-2025,Cash
3,1004,NaN,user3@yahoo.com,bangalore,Keyboard,3.0,8000.0,5.0,2025-01-05,card
4,1005,Priya,NaN,Belagavi,Laptop,5.0,1200.0,4.0,06-01-2025,UPI

In [8]:
df.tail()

,Order_ID,Customer_Name,Email,City,Product,Quantity,Price,Customer_Rating,Order_Date,Payment_Method
195,1196,Priya,NaN,Bengaluru,Monitor,5.0,45000.0,5.0,06-01-2025,UPI
196,1197,Amit,NaN,bangalore,Monitor,NaN,1200.0,3.0,NaN,Cash
197,1198,Ravi,user197@gmail.com,BLR,Keyboard,2.0,45000.0,1.0,06-01-2025,UPI
198,1199,Ravi,user198gmail.com,NaN,Monitor,-1.0,500.0,2.0,2025/01/07,UPI
199,1200,Amit,user199@gmail.com,BLR,Headphone,NaN,-100.0,5.0,06-01-2025,NaN

In [9]:
df.dtypes

Order_ID             int64
Customer_Name       object
Email               object
City                object
Product             object
Quantity           float64
Price              float64
Customer_Rating    float64
Order_Date          object
Payment_Method      object
dtype: object

In [11]:
df.isnull().sum()

Order_ID            0
Customer_Name      23
Email              53
City               17
Product             0
Quantity           29
Price              34
Customer_Rating    29
Order_Date         39
Payment_Method     22
dtype: int64

In [13]:
(df.isnull().mean()*100).round()

Order_ID            0.0
Customer_Name      12.0
Email              26.0
City                8.0
Product             0.0
Quantity           14.0
Price              17.0
Customer_Rating    14.0
Order_Date         20.0
Payment_Method     11.0
dtype: float64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['Order_ID'].duplicated().sum()

np.int64(7)

In [19]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Order_ID,200.0,1097.000000,59.983247,1001.0,1044.75,1096.5,1148.25,1200.0
Quantity,171.0,2.169591,2.092117,-1.0,1.00,2.0,3.00,5.0
Price,166.0,12742.771084,18185.599752,-100.0,500.00,1200.0,8000.00,45000.0
Customer_Rating,171.0,2.842105,2.257975,-1.0,1.00,3.0,5.00,6.0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         200 non-null    int64
 1   Customer_Name    177 non-null    object
 2   Email            147 non-null    object
 3   City             183 non-null    object
 4   Product          200 non-null    object
 5   Quantity         171 non-null    float64
 6   Price            166 non-null    float64
 7   Customer_Rating  171 non-null    float64
 8   Order_Date       161 non-null    object
 9   Payment_Method   178 non-null    object
dtypes: float64(3), int64(1), object(6)
memory usage: 15.8+ KB

In [23]:
df['Customer_Name'].nunique()

7

In [24]:
df['Customer_Name'].unique()

array(['Ravi', 'Amit', 'Omkar', nan, 'Priya', 'Rahul', 'omkar', 'Sneha'],
      dtype=object)

#

# Data Cleaning

In [25]:
df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')

In [27]:
df['Customer_Name'] = df['Customer_Name'].replace('', 'Unknown')

In [28]:
df['Email'] = df['Email'].astype(str)

In [30]:
mask = df['Email'].str.contains(r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$', regex=True, na=False)

In [32]:
df.loc[~mask, 'Email'] = np.nan

#

In [33]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Email', 'City', 'Product', 'Quantity',
       'Price', 'Customer_Rating', 'Order_Date', 'Payment_Method'],
      dtype='object')

In [34]:
df['City'].unique()

array(['Belagavi', 'Belgaum', ' bangalore ', nan, 'Bengaluru',
       'Bangalore', 'BLR'], dtype=object)

In [35]:
df['City'] = df['City'].astype(str).str.strip().str.title()

In [36]:
city_map = {
    'Blr':'Bangalore',
    'Bengaluru':'Bangalore',
    'Belagavi':'Belgaum'
}

In [37]:
df['City'] = df['City'].replace(city_map)

#

In [41]:
df['Product'].unique()

array(['Headphone', 'Laptop', 'Keyboard', 'Mouse', 'Monitor'],
      dtype=object)

#

In [42]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [43]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

In [44]:
df['Customer_Rating'] = pd.to_numeric(df['Customer_Rating'], errors='coerce')

#

In [49]:
df.loc[df['Quantity'] <= 0, 'Quantity'] = np.nan

In [52]:
df.loc[df['Price'] <= 0, 'Price'] = np.nan

In [53]:
df.loc[~df['Customer_Rating'].between(1,5), 'Customer_Rating'] = np.nan

#

In [54]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

In [59]:
df['Price'] = df['Price'].fillna(df['Price'].median())

In [60]:
df['Customer_Rating'] = df['Customer_Rating'].fillna(df['Customer_Rating'].median())

#

In [61]:
df['Payment_Method'] = df['Payment_Method'].replace('', np.nan)

In [64]:
df['Payment_Method'] = df['Payment_Method'].fillna('Unknown')

In [65]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce', format='mixed')

In [66]:
print(df.isnull().sum())

Order_ID             0
Customer_Name        0
Email              106
City                 0
Product              0
Quantity             0
Price                0
Customer_Rating      0
Order_Date          39
Payment_Method       0
dtype: int64