# One-Sample T-Test: Business Case Studies

In [1]:
import numpy as np
import pandas as pd 
import scipy.stats as stats

### Case 1 – FastTrack Logistics

#### Business Problem

- FastTrack Logistics has always taken 4.5 days on average to deliver orders. Recently, the company introduced an AI-powered route optimization system to help drivers choose faster routes and reduce delivery time.

- The management wants to know if the new system is actually improving delivery speed before using it across all regions.

#### Business Question
- Has the average delivery time become less than 4.5 days after implementing the AI routing system?

In [2]:
data_df = pd.read_csv('delivery_sample_after_ai_routing.csv')

In [3]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shipment_ID         75 non-null     object
 1   Delivery_Date       75 non-null     object
 2   Origin_City         75 non-null     object
 3   Destination_City    75 non-null     object
 4   Product_Category    75 non-null     object
 5   Delivery_Channel    75 non-null     object
 6   Distance_KM         75 non-null     float64
 7   Driver_ID           75 non-null     object
 8   Delivery_Time_Days  75 non-null     float64
dtypes: float64(2), object(7)
memory usage: 5.4+ KB

In [4]:
data_df.head()

,Shipment_ID,Delivery_Date,Origin_City,Destination_City,Product_Category,Delivery_Channel,Distance_KM,Driver_ID,Delivery_Time_Days
0,SHP10000,2025-01-19,Kolkata,Bhopal,Groceries,Express,1300.7,DRV119,3.36
1,SHP10001,2025-01-20,Chennai,Patna,Pharmacy,Standard,893.1,DRV177,5.21
2,SHP10002,2025-02-02,Ahmedabad,Patna,Pharmacy,Express,881.6,DRV144,4.25
3,SHP10003,2025-02-09,Ahmedabad,Nagpur,Books,Standard,1400.8,DRV181,4.46
4,SHP10004,2025-01-16,Ahmedabad,Surat,Toys,Express,471.2,DRV136,3.97

In [5]:
data_df.duplicated().sum()

np.int64(0)

In [7]:
sample1 = data_df['Delivery_Time_Days']

#

#### Hypotheses
- H0 = 4.5 days - Null Hypothesis
- H1 < 4.5 days - Alternative Hypothesis   
Test : Left-Tailed T-test

In [13]:
mean1 = 4.5

In [14]:
sample_mean1 = sample1.mean()

In [15]:
sample_std1 = sample1.std()
sample_size1 = len(sample1)

In [18]:
print('Sample Mean : ',sample_mean1)
print('Sample Std  : ', sample_std1)
print('Sample Sizxe : ', sample_size1)

Sample Mean :  4.277333333333334
Sample Std  :  0.7086193910989461
Sample Sizxe :  75

In [20]:
T1 = (sample_mean1 - mean1)/(sample_std1/np.sqrt(sample_size1))

In [21]:
T1

np.float64(-2.7212773504586267)

In [27]:
alpha = 0.05
dof = sample_size1 - 1
t_critical1 = stats.t.ppf(alpha, dof)

In [28]:
t_critical1

np.float64(-1.6657068927340237)

In [30]:
if T1 < t_critical1:
    print("Decision: REJECT H0")
    print("Conclusion: Sufficient evidence that mean delivery time < 4.5 days")
else:
    print("Decision: FAIL TO REJECT H0")
    print("Conclusion: Not enough evidence that mean delivery time < 4.5 days")

Decision: REJECT H0
Conclusion: Sufficient evidence that mean delivery time < 4.5 days

#

#

### Case 2 – CloudSync Analytics

#### Business Problem

- CloudSync Analytics redesigned its analytics dashboard to improve user experience and keep users engaged for a longer time. Before the redesign, users spent an average of 25 minutes per day in the app.

- The product team wants to know if the new dashboard has actually increased user engagement before presenting the results to the company's board.

#### Business Question

- Has the average daily user engagement increased above 25 minutes after the dashboard redesign?

In [33]:
data_df2=  pd.read_csv('user_engagement_after_dashboard_update.csv')

In [34]:
data_df2.head()

,User_ID,Signup_Date,Plan_Type,Device,Region,Customer_Segment,Session_Date,Engagement_Minutes
0,USR20000,2024-08-31,Enterprise,Mobile,North America,SMB,2025-02-23,28.4
1,USR20001,2024-08-22,Pro,Mobile,LATAM,Mid-Market,2025-01-09,21.3
2,USR20002,2024-06-26,Enterprise,Mobile,LATAM,Mid-Market,2025-02-15,36.3
3,USR20003,2024-02-03,Basic,Desktop,APAC,Mid-Market,2025-01-08,28.0
4,USR20004,2023-12-25,Basic,Mobile,LATAM,SMB,2025-01-11,23.0

In [35]:
data_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_ID             80 non-null     object
 1   Signup_Date         80 non-null     object
 2   Plan_Type           80 non-null     object
 3   Device              80 non-null     object
 4   Region              80 non-null     object
 5   Customer_Segment    80 non-null     object
 6   Session_Date        80 non-null     object
 7   Engagement_Minutes  80 non-null     float64
dtypes: float64(1), object(7)
memory usage: 5.1+ KB

In [37]:
data_df2.duplicated().sum()

np.int64(0)

In [38]:
sample2 = data_df2['Engagement_Minutes']

In [39]:
sample2.head()

0    28.4
1    21.3
2    36.3
3    28.0
4    23.0
Name: Engagement_Minutes, dtype: float64

#### Hypotheses
- H0 = 25 minutes- Null Hypothesis
- H1 > 25 minutes- Alternative Hypothesis   
Test : Right-Tailed T-test

In [41]:
mean2 = 25

In [42]:
sample_mean2 = sample2.mean()
sample_std2 = sample2.std()
sample_size2 = len(sample2)

In [45]:
print('Sample Mean : ', sample_mean2)
print('Sample Std  : ', sample_std2)
print('Sample Size : ', sample_size2)

Sample Mean :  27.013749999999998
Sample Std  :  5.479391626352027
Sample Size :  80

In [50]:
T2_test = (sample_mean2 - mean2)/(sample_std2/np.sqrt(sample_size2))

In [51]:
T2_test

np.float64(3.287140030681141)

In [59]:
alpha = 0.05
dof2 = sample_size2 - 1
critical_t2 = stats.t.ppf(1-alpha, dof2)

In [60]:
critical_t2

np.float64(1.6643714091975021)

In [62]:
if T2_test > t_critical1:
    print("Decision: REJECT H0")
    print("Average user engagement has increased above 25 minutes.")
else:
    print("Decision: FAIL TO REJECT H0")
    print("There is not enough evidence that average user engagement has increased above 25 minutes.")

Decision: REJECT H0
Average user engagement has increased above 25 minutes.

#

#

### Case 3 – Banking (Meridian National Bank)

#### Business Problem

- Meridian National Bank's service level agreement (SLA) states that loan applications should be processed in 6 days on average. Recently, the internal audit team received complaints that processing times may have changed due to increased workload or a new digital workflow.

- The bank wants to check whether the current average processing time is still 6 days or if it has changed.

#### Business Question

- Is the average loan processing time different from the SLA benchmark of 6 days?

In [63]:
data_df3 = pd.read_csv('loan_processing_time_audit_sample.csv')

In [65]:
data_df3.head()

,Loan_ID,Application_Date,Branch_City,Loan_Type,Customer_ID,Channel,Loan_Amount_INR,Officer_ID,Processing_Time_Days
0,LN30000,2025-03-15,Hyderabad Gachibowli,Business Loan,CUST40000,Branch,463230.0,OFC46,6.6
1,LN30001,2025-05-11,Kolkata Salt Lake,Business Loan,CUST40001,Online,857370.0,OFC31,6.2
2,LN30002,2025-05-19,Delhi CP,Personal Loan,CUST40002,Branch,3555906.0,OFC58,6.2
3,LN30003,2025-04-28,Pune Kothrud,Auto Loan,CUST40003,Branch,1666103.0,OFC10,6.6
4,LN30004,2025-04-24,Chennai T Nagar,Home Loan,CUST40004,Online,1606723.0,OFC33,7.7

In [66]:
data_df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Loan_ID               70 non-null     object
 1   Application_Date      70 non-null     object
 2   Branch_City           70 non-null     object
 3   Loan_Type             70 non-null     object
 4   Customer_ID           70 non-null     object
 5   Channel               70 non-null     object
 6   Loan_Amount_INR       70 non-null     float64
 7   Officer_ID            70 non-null     object
 8   Processing_Time_Days  70 non-null     float64
dtypes: float64(2), object(7)
memory usage: 5.1+ KB

In [67]:
data_df3.duplicated().sum()

np.int64(0)

In [68]:
sample3 = data_df3['Processing_Time_Days']

In [69]:
sample3.head()

0    6.6
1    6.2
2    6.2
3    6.6
4    7.7
Name: Processing_Time_Days, dtype: float64

#### Hypotheses
- H0 = 6 days - Null Hypothesis
- H1 != 6 days - Alternative Hypothesis   
Test : Two-Tailed T-test

In [71]:
mean3 = 6

In [73]:
sample_mean3 = sample3.mean()
sample_std3 = sample3.std()
sample_size3 = len(sample3)

In [75]:
print('Sample Mean : ', sample_mean3)
print('Sample Std  : ', sample_std3)
print('Sample Size : ', sample_size3)

Sample Mean :  6.870000000000001
Sample Std  :  1.8402386423693984
Sample Size :  70

In [76]:
T3_test = (sample_mean3 - mean3) / (sample_std3 / np.sqrt(sample_size3))

In [77]:
T3_test

np.float64(3.9554338569232885)

In [82]:
alpha = 0.05
dof3 = sample_size3 -1
left_critical = stats.t.ppf(alpha/2, dof3)
right_critical = stats.t.ppf(1 - alpha/2, dof3)

In [83]:
left_critical

np.float64(-1.9949454151072379)

In [84]:
right_critical

np.float64(1.9949454151072374)

In [ ]:
if T3_test < left_critical or T3_test > right_critical:
    print("Reject H0")
    print("Average loan processing time is different from 6 days.")
else:
    print("Fail to Reject H0")
    print("Average loan processing time is not significantly different from 6 days.")

Reject H₀
Average loan processing time is different from 6 days.