# Measures of Central Tendency

In [1]:
import pandas as pd
import numpy as np
import statistics

#### Retail Sales Analysis

In [2]:
# load dataset 
data = pd.read_excel('retail_sales_dummy_500.xlsx')

In [3]:
data.head()

,Order_ID,Customer_ID,Category,Quantity,Unit_Price,Sales,Discount,Payment_Method
0,1,1081,Office Supplies,5,145,725,0,UPI
1,2,1069,Office Supplies,7,36,252,5,Card
2,3,1077,Office Supplies,4,299,1196,15,UPI
3,4,1000,Furniture,3,1165,3495,5,Card
4,5,1097,Office Supplies,2,214,428,10,UPI

In [5]:
# Explore the Dataset
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Order_ID,500.0,250.500,144.481833,1.0,125.75,250.5,375.25,500.0
Customer_ID,500.0,1051.840,29.324089,1000.0,1026.75,1052.5,1077.25,1100.0
Quantity,500.0,5.686,2.851608,1.0,3.00,6.0,8.00,10.0
Unit_Price,500.0,928.896,2584.340446,20.0,168.00,309.5,1165.75,46580.0
Sales,500.0,5313.278,14393.030789,40.0,678.75,1871.0,5944.50,279480.0
Discount,500.0,10.480,6.997681,0.0,5.00,10.0,15.00,20.0

In [6]:
# average sales amount
data['Sales'].mean()

np.float64(5313.278)

In [7]:
statistics.mean(data['Sales'])

5313.278

In [10]:
# typical customer spending
data['Sales'].median()

1871.0

In [12]:
statistics.median(data['Sales'])

1871.0

In [15]:
print(data["Sales"].mean())
print(data["Sales"].median())

5313.278
1871.0

##### Mean > Median	Positively skewed [Right-skewed]

#

In [16]:
data.columns

Index(['Order_ID', 'Customer_ID', 'Category', 'Quantity', 'Unit_Price',
       'Sales', 'Discount', 'Payment_Method'],
      dtype='object')

In [17]:
# Most sold category
data['Category'].mode()

0    Office Supplies
Name: Category, dtype: object

In [19]:
statistics.mode(data['Category'])

'Office Supplies'

In [20]:
# Most common payment method
data['Payment_Method'].mode()

0    Card
Name: Payment_Method, dtype: object

In [22]:
statistics.mode(data['Payment_Method'])

'Card'

In [23]:
# Average selling price considering quantity sold.
# waighted mean
np.average(data["Unit_Price"],weights=data["Quantity"])

np.float64(934.4491734083714)

In [25]:
data["Unit_Price"].mean()

np.float64(928.896)

In [29]:
data[["Unit_Price","Quantity"]].head(10)

   Unit_Price  Quantity
0         145         5
1          36         7
2         299         4
3        1165         3
4         214         2
5        1011         9
6        1040        10
7         776         2
8        1058         3
9        1200        10

In [31]:
# Some observations are more important than others
# so that the reason  weighted mean  is this better than mean

#

##### Trimmed Mean

In [32]:
from scipy.stats import trim_mean

In [34]:
trim_mean(data["Sales"],0.10)

np.float64(3222.055)

In [36]:
trim_mean(data["Sales"],0.20)

np.float64(2601.4933333333333)

In [37]:
# removing a fixed percentage of the smallest and largest observations and calculate mean 
# useful when outlier are presant in dataset

#

##### Category-wise Mean

In [39]:
data.groupby("Category")["Sales"].mean()

Category
Furniture           5503.190476
Office Supplies     1269.691406
Technology         13883.016949
Name: Sales, dtype: float64

In [40]:
# we can understand which category have better sales or performance

##### Category-wise Median

In [41]:
data.groupby("Category")["Sales"].median()

Category
Furniture          4306.0
Office Supplies     741.0
Technology         9506.0
Name: Sales, dtype: float64

In [43]:
# usefull to check performance when data contain outliers

#### Which payment method has the highest average order value?

In [44]:
data.groupby("Payment_Method")["Sales"].mean()

Payment_Method
Card          5986.061538
Cash          5118.886364
NetBanking    5567.750000
UPI           4066.034722
Name: Sales, dtype: float64

#

#### Does a higher discount lead to higher sales

In [50]:
data.groupby("Discount")["Sales"].mean()

Discount
0     4444.258427
5     7869.522222
10    4223.121739
15    3982.802083
20    6225.772727
Name: Sales, dtype: float64

##### How does quantity affect sales?

In [49]:
data.groupby("Quantity")["Sales"].mean()

Quantity
1      625.470588
2     1650.851852
3     2153.450000
4     5066.782609
5     4369.565217
6     9825.658537
7     7213.714286
8     7552.500000
9     7812.666667
10    6180.384615
Name: Sales, dtype: float64