# Binomial Distribution – Online Shoppers Purchasing Intention

In [1]:
import pandas as pd 
from scipy.stats import binom

In [2]:
data = pd.read_csv('online_shoppers_intention.csv')

In [3]:
data.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [5]:
purchase_rate=data['Revenue'].mean()

In [6]:
purchase_rate

np.float64(0.15474452554744525)

#### 1. First calculate the overall purchase rate p (fraction of sessions where Revenue = True) from the dataset.

In [8]:
print('Purchase Rate: ',round(purchase_rate,2))

Purchase Rate:  0.15

#### 2. If 100 random visitors come to the site today, what's the expected number of purchases (n × p)? Do this simple multiplication first before anything fancier.

###### If 100 people visit today, about how many people are expected to buy something?

In [15]:
purchase_rate*100

np.float64(15.474452554744525)

#### 3. Using that same p, what's the probability that out of 100 visitors, more than 20 actually purchase? (Use binomial formula or Normal approximation since n is large.)

###### What is the chance that at least 20 out of 100 visitors will make a purchase?

In [19]:
binom.sf(20,100,purchase_rate)

np.float64(0.08604190588411718)

#### 4. Marketing runs a flash sale expecting a lift to p = 0.20 (from whatever the baseline is). Out of 200 visitors during the sale, what's the probability at least 50 purchase?

###### If the flash sale increases the buying rate to 20%, what is the chance that 50 or more out of 200 visitors will buy?

In [22]:
binom.sf(50,200,0.20)

np.float64(0.034496774865728844)

#### 5. The Weekend column splits sessions into weekend vs weekday. Compute purchase rate p separately for each. If 150 people visit this weekend, what's the expected number of purchases using the weekend-specific p?

###### Do weekend visitors buy more? If 150 people visit this weekend, how many purchases should we expect?

In [23]:
w = (data['Weekend']==True).mean()

In [24]:
w

np.float64(0.23260340632603407)

In [25]:
wDays = (data['Weekend']==False).mean()
wDays

np.float64(0.767396593673966)

In [27]:
expected_purchases = 150 * w

In [28]:
expected_purchases

np.float64(34.89051094890511)

#

#### 6. A site reliability question: bounce rate (BounceRates column, sessions where people leave immediately) — treat "bounced" as a success/failure trial. Out of 500 sessions, what's the probability more than 100 bounce, given the historical bounce rate?

###### Based on past data, what is the chance that more than 100 out of 500 visitors leave the website immediately?

In [29]:
data.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [34]:
br = data['BounceRates'].mean() 
binom.sf(100,500,br)

np.float64(1.0567245880711925e-63)

In [35]:
b=(data['BounceRates']>0).mean()

In [33]:
binom.sf(100,500,br)

np.float64(1.0567245880711925e-63)

###### The probability of more than 100 visitors bouncing is almost zero.

#

#### 7 . What is the probability that more than 40 out of 250 visitors have a valuable session (PageValues > 0)?

In [38]:
data['PageValues'].unique()[:5]

array([ 0.        , 54.17976426, 19.44707913, 38.30849268, 22.9160357 ])

In [39]:
pvr = (data['PageValues']>0).mean()

In [40]:
pvr

np.float64(0.22141119221411193)

In [41]:
binom.sf(40,250,pvr)

np.float64(0.9901145721899415)

#### 8. If 100 visitors using Browser 1 visit the website, how many purchases are expected based on the historical purchase rate?

In [45]:
browser_rate = data[data['Browser'] == 1]['Revenue'].mean()

In [46]:
browser_rate

np.float64(0.14825345247766045)

In [47]:
expected = browser_rate *100

In [48]:
print("Expected Purchases:", expected)

Expected Purchases: 14.825345247766045

###### means 14.82% of Browser 1 visitors make a purchase.

#

#### 9. What is the probability that at least 70 out of 300 visitors view more than 20 product pages?

In [51]:
view_rate = (data['ProductRelated'] > 20).mean()

In [52]:
view_rate

np.float64(0.45393349553933493)

In [53]:
binom.sf(70, 300,view_rate)

np.float64(0.9999999999999981)

###### There is an almost 100% chance that at least 70 out of 300 visitors will view more than 20 product pages

#### 10.  What is the probability that more than 60 out of 200 visitors access at least one administrative page?

In [55]:
data['Administrative'].unique()

array([ 0,  1,  2,  4, 12,  3, 10,  6,  5,  9,  8, 16, 13, 11,  7, 18, 14,
       17, 19, 15, 24, 22, 21, 20, 23, 27, 26])

In [56]:
admin_rate = (data['Administrative']>0).mean()

In [57]:
admin_rate

np.float64(0.5321978913219789)

In [58]:
pb = binom.sf(60,200,admin_rate)

In [59]:
pb

np.float64(0.9999999999736557)

#

#### 11. If 500 visitors arrive, what is the probability that more than 150 have an Exit Rate above the dataset average?

In [63]:
exit_rate = (data['ExitRates'] > data['ExitRates'].mean()).mean()

In [64]:
exit_rate

np.float64(0.2869424168694242)

In [66]:
binom.sf(150, 500, exit_rate)

np.float64(0.24243015054313258)

#

#### 12 . What is the probability that more than 80 out of 300 visitors are Returning Visitors?

In [67]:
data.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [77]:
data['VisitorType'].unique()

array(['Returning_Visitor', 'New_Visitor', 'Other'], dtype=object)

In [78]:
data['VisitorType'].value_counts()

VisitorType
Returning_Visitor    10551
New_Visitor           1694
Other                   85
Name: count, dtype: int64

In [81]:
returning_rate = (data['VisitorType'] == 'Returning_Visitor').mean()

In [82]:
returning_rate

np.float64(0.8557177615571776)

In [85]:
binom.sf(80, 300, returning_rate)

np.float64(1.0)

###### Probability = 1.0 (100%)

#

#### 13. If 200 visitors arrive, how many are expected to visit more than 10 product pages?

In [89]:
high_product_rate = (data['ProductRelated'] > 10).mean()

In [90]:
high_product_rate

np.float64(0.6615571776155718)

In [91]:
high_product_rate * 200

np.float64(132.31143552311434)

#

#### 14. What is the probability that at least 30 out of 150 visitors spend time on informational pages?

In [93]:
info_rate = (data['Informational'] > 0).mean()

In [95]:
info_rate

np.float64(0.21338199513381995)

In [96]:
binom.sf(29, 150, info_rate)

np.float64(0.6861701699247922)

#

#### 15. What is the probability that less than 100 out of 400 visitors use Operating System 2?

In [98]:
os_rate = (data['OperatingSystems'] == 2).mean()

In [103]:
binom.cdf(100, 400, os_rate)

np.float64(3.1390189926404986e-31)