# Data Inspection

In [1]:
import pandas as pd

## 🔹 Basic Inspection

#### 1. Load a CSV file and display first 10 rows

In [2]:
data = pd.read_csv('Sale.csv')

In [3]:
data.head(10)

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,07-11-2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,07-11-2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,07-11-2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,08-11-2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,08-11-2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin
5,10457,08-11-2022,Fries,3.49,573.07,In-store,Credit Card,Remy Monet,Paris
6,10459,08-11-2022,Sides & Other,4.99,200.40,In-store,Credit Card,Walter Muller,Berlin
7,10460,09-11-2022,Burgers,12.99,554.27,In-store,Credit Card,Remy Monet,Paris
8,10461,09-11-2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Remy Monet,Paris
9,10462,09-11-2022,Fries,3.49,573.07,In-store,Credit Card,Remy Monet,Paris

#### 2. Show last 5 rows of dataset

In [4]:
data.tail()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
249,10709,28-12-2022,Sides & Other,4.99,200.40,Drive-thru,Gift Card,Walter Muller,Berlin
250,10710,29-12-2022,Burgers,12.99,754.43,Drive-thru,Gift Card,Walter Muller,Berlin
251,10711,29-12-2022,Chicken Sandwiches,9.95,281.41,Drive-thru,Gift Card,Walter Muller,Berlin
252,10712,29-12-2022,Fries,3.49,630.37,Drive-thru,Gift Card,Walter Muller,Berlin
253,10713,29-12-2022,Beverages,2.95,677.97,Drive-thru,Gift Card,Walter Muller,Berlin

#### 3. Find total number of rows and columns

In [6]:
rows , cols = data.shape
print("Total Rows :",rows)
print("Total columns :",cols)

Total Rows : 254
Total columns : 9

#### 4. Display column names

In [8]:
print(data.columns)

Index(['Order ID', 'Date', 'Product', 'Price', 'Quantity', 'Purchase Type',
       'Payment Method', 'Manager', 'City'],
      dtype='object')

#### 5. Check data types of each column

In [9]:
data.dtypes

Order ID            int64
Date               object
Product            object
Price             float64
Quantity          float64
Purchase Type      object
Payment Method     object
Manager            object
City               object
dtype: object

#### 6. Get summary statistics of numerical columns

In [10]:
data.describe()

           Order ID       Price    Quantity
count    254.000000  254.000000  254.000000
mean   10584.133858    7.102323  460.611457
std       75.889181    4.341855  214.888699
min    10452.000000    2.950000  200.400000
25%    10520.250000    3.490000  201.010000
50%    10583.500000    4.990000  538.880000
75%    10649.750000    9.950000  677.440000
max    10713.000000   29.050000  754.430000

#### 7. Get summary of all columns (including object type)

In [11]:
data.describe(include='all')

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
count,254.000000,254,254,254.000000,254.000000,254,254,254,254
unique,NaN,53,5,NaN,NaN,3,3,14,5
top,NaN,09-11-2022,Chicken Sandwiches,NaN,NaN,Online,Credit Card,Tom Jackson,London
freq,NaN,5,52,NaN,NaN,107,120,74,75
mean,10584.133858,NaN,NaN,7.102323,460.611457,NaN,NaN,NaN,NaN
std,75.889181,NaN,NaN,4.341855,214.888699,NaN,NaN,NaN,NaN
min,10452.000000,NaN,NaN,2.950000,200.400000,NaN,NaN,NaN,NaN
25%,10520.250000,NaN,NaN,3.490000,201.010000,NaN,NaN,NaN,NaN
50%,10583.500000,NaN,NaN,4.990000,538.880000,NaN,NaN,NaN,NaN
75%,10649.750000,NaN,NaN,9.950000,677.440000,NaN,NaN,NaN,NaN
max,10713.000000,NaN,NaN,29.050000,754.430000,NaN,NaN,NaN,NaN

#### 8. Find memory usage of dataset

In [12]:
data.memory_usage()

Index              132
Order ID          2032
Date              2032
Product           2032
Price             2032
Quantity          2032
Purchase Type     2032
Payment Method    2032
Manager           2032
City              2032
dtype: int64

In [13]:
data.memory_usage(deep=True)

Index               132
Order ID           2032
Date              14986
Product           15088
Price              2032
Quantity           2032
Purchase Type     14640
Payment Method    14846
Manager           15293
City              13942
dtype: int64

## 🔹 Understanding Data Quality

#### 9. Identify columns with missing values

In [14]:
data.isnull()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
249,False,False,False,False,False,False,False,False,False
250,False,False,False,False,False,False,False,False,False
251,False,False,False,False,False,False,False,False,False
252,False,False,False,False,False,False,False,False,False
253,False,False,False,False,False,False,False,False,False

In [15]:
data.columns[data.isnull().any()]

Index([], dtype='object')

#

In [18]:
data2 = pd.read_csv("Dataset2.csv")

In [19]:
data2.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [20]:
data2.columns[data2.isnull().any()]

Index(['Glucose', 'Diastolic_BP', 'Skin_Fold', 'Serum_Insulin', 'BMI'], dtype='object')

#### 10. Count total missing values in dataset

In [21]:
data2.isnull().sum()

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [108]:
data2.isnull().sum().sum()

np.int64(652)

#### 11. Find percentage of missing values per column

In [24]:
missing_per = round((data2.isnull().sum() /len(data2))*100)

In [25]:
missing_per

Pregnant              0.0
Glucose               1.0
Diastolic_BP          5.0
Skin_Fold            30.0
Serum_Insulin        49.0
BMI                   1.0
Diabetes_Pedigree     0.0
Age                   0.0
Class                 0.0
dtype: float64

In [27]:
round((data2.isnull().mean() * 100))

Pregnant              0.0
Glucose               1.0
Diastolic_BP          5.0
Skin_Fold            30.0
Serum_Insulin        49.0
BMI                   1.0
Diabetes_Pedigree     0.0
Age                   0.0
Class                 0.0
dtype: float64

#### 12. Check if dataset has any null values (True/False)

In [31]:
data2.isnull().any()

Pregnant             False
Glucose               True
Diastolic_BP          True
Skin_Fold             True
Serum_Insulin         True
BMI                   True
Diabetes_Pedigree    False
Age                  False
Class                False
dtype: bool

In [32]:
data2.isnull().values.any()

np.True_

In [29]:
data.isnull().values.any()

np.False_

In [109]:
data2.isnull().any().any()

np.True_

#### 13. Identify column with maximum missing data

In [33]:
data.isnull().sum().idxmax()

'Order ID'

In [34]:
data2.isnull().sum().idxmax()

'Serum_Insulin'

## 🔹 Unique & Value Analysis

#### 14. Find unique values in a column

In [37]:
data.columns

Index(['Order ID', 'Date', 'Product', 'Price', 'Quantity', 'Purchase Type',
       'Payment Method', 'Manager', 'City'],
      dtype='object')

In [39]:
data['Product'].unique()

array(['Fries', 'Beverages', 'Sides & Other', 'Burgers',
       'Chicken Sandwiches'], dtype=object)

In [41]:
data.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

#### 15. Count number of unique values in each column

In [42]:
data.nunique()

Order ID          254
Date               53
Product             5
Price               7
Quantity           29
Purchase Type       3
Payment Method      3
Manager            14
City                5
dtype: int64

#### 16. Find most frequent value in a column

In [44]:
data["Product"].idxmax() # wrong

2

In [46]:
data['Product'].mode()

0               Burgers
1    Chicken Sandwiches
Name: Product, dtype: object

In [45]:
data['Product'].mode()[0]

'Burgers'

#### 17. Display frequency count of a categorical column

In [47]:
data['Product'].value_counts()

Product
Chicken Sandwiches    52
Burgers               52
Fries                 51
Beverages             50
Sides & Other         49
Name: count, dtype: int64

#### 18. Identify columns with only one unique value

In [51]:
data.nunique()[data.nunique() == 1]

Series([], dtype: int64)

In [52]:
data.columns[data.nunique() == 1]

Index([], dtype='object')

In [53]:
import numpy as np

In [54]:
dict_data = {
    "A" :  np.full(5,1),
    "B" : np.random.random(5),
    "C" : np.random.rand(5)
}
df = pd.DataFrame(dict_data)

In [57]:
df.nunique()[df.nunique() == 1]

A    1
dtype: int64

In [58]:
df.columns[df.nunique()==1]

Index(['A'], dtype='object')

## 🔹 Duplicate & Consistency Check

#### 19. Check total duplicate rows

In [59]:
data.duplicated().sum()

np.int64(0)

In [63]:
data2.duplicated().sum()

np.int64(0)

In [64]:
data3 =  pd.read_csv("dataset3.csv")

In [66]:
data3.duplicated().sum()

np.int64(3)

#### 20. Show duplicate rows

In [67]:
data3[data3.duplicated()]

    id  name   age   city   salary
5    3  Sita  20.0  Delhi  20000.0
15   3  Sita  20.0  Delhi  20000.0
25  11  John  22.0   Pune  50000.0

#### 21. Identify duplicate values in a specific column

In [68]:
data3.columns

Index(['id', 'name', 'age', 'city', 'salary'], dtype='object')

In [70]:
data3['name'].duplicated().sum()

np.int64(94)

In [71]:
data3['city'].duplicated().sum()

np.int64(94)

In [72]:
data3['name']

0     John
1     Neha
2     Sita
3     Neha
4     Neha
      ...
95    John
96    John
97    Neha
98    Amit
99    Neha
Name: name, Length: 100, dtype: object

In [73]:
data3['name'].nunique()

6

## 🔹 Data Distribution Understanding

#### 22. Find min, max, mean of a column

In [75]:
data3.describe()

               id        age        salary
count  100.000000  85.000000     82.000000
mean    50.190000  21.858824  33414.634146
std     29.407858   1.456945  11463.254466
min      1.000000  20.000000  20000.000000
25%     24.750000  20.000000  20000.000000
50%     50.500000  22.000000  30000.000000
75%     75.250000  23.000000  40000.000000
max    100.000000  24.000000  50000.000000

In [78]:
data3['age'].min()

20.0

In [79]:
data3['age'].max()

24.0

In [82]:
print(np.round(data3['age'].mean()))

22.0

#### 23. Identify column with highest average value`

In [85]:

data3.mean().idxmax()

TypeError: can only concatenate str (not "int") to str

In [87]:
data3.mean(numeric_only=True).idxmax()

'salary'

#### 24. Check standard deviation of numerical columns

In [89]:
data3.std(numeric_only=True)

id           29.407858
age           1.456945
salary    11463.254466
dtype: float64

#### 25. Find skewness of data

In [90]:
data3.skew(numeric_only=True)

id       -0.021259
age       0.038463
salary    0.199098
dtype: float64

## 🔹 Column-wise Deep Inspection

#### 26. Inspect a single column completely

In [91]:
data.columns

Index(['Order ID', 'Date', 'Product', 'Price', 'Quantity', 'Purchase Type',
       'Payment Method', 'Manager', 'City'],
      dtype='object')

In [92]:
data['Product'].describe()

count                    254
unique                     5
top       Chicken Sandwiches
freq                      52
Name: Product, dtype: object

In [93]:
data['Purchase Type'].describe()

count         254
unique          3
top       Online
freq          107
Name: Purchase Type, dtype: object

#### 27.Check datatype + null + unique values of one column

In [94]:
data3.columns

Index(['id', 'name', 'age', 'city', 'salary'], dtype='object')

In [101]:
data3['age'].dtype

dtype('float64')

In [102]:
data3['age'].isnull().sum()

np.int64(15)

In [103]:
data3['age'].unique()

array([24., 20., 22., 21., 23., nan])

#### 28. Find columns with numeric data only

In [106]:
data3.select_dtypes(include='number').columns

Index(['id', 'age', 'salary'], dtype='object')

#### 29. Find columns with object/string type

In [107]:
data3.select_dtypes(include='object').columns

Index(['name', 'city'], dtype='object')