# DATA CLEANING` 10

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('messy_data9.csv')

In [3]:
df = data.copy()

#

In [4]:
df.shape

(500, 6)

In [5]:
df.head()

,Customer_ID,Full_Name,Email,Purchase_Date,Amount_Spent,City
0,CUST_0362,Mark Davis,not_an_email_361,NaN,470.12,Charlotte
1,CUST_0074,John Miller,james.lopezgmail.com,2023-11-01,313.9,Chicago
2,CUST_0375,Nancy Brown,susan.wright@yahoo.com,09/30/2023,-111.5,NaN
3,CUST_0156,Sarah Ramirez,karen.jones@yahoo.com,2024-07-29,-182.61,Baltimore
4,CUST_0105,Susan Moore,sarah741.allen@gmail.com,2023-09-24,389.22,Las Vegas

In [6]:
df.head(10)

,Customer_ID,Full_Name,Email,Purchase_Date,Amount_Spent,City
0,CUST_0362,Mark Davis,not_an_email_361,NaN,470.12,Charlotte
1,CUST_0074,John Miller,james.lopezgmail.com,2023-11-01,313.9,Chicago
2,CUST_0375,Nancy Brown,susan.wright@yahoo.com,09/30/2023,-111.5,NaN
3,CUST_0156,Sarah Ramirez,karen.jones@yahoo.com,2024-07-29,-182.61,Baltimore
4,CUST_0105,Susan Moore,sarah741.allen@gmail.com,2023-09-24,389.22,Las Vegas
5,CUST_0395,Karen!!! Lopez??,matthew712.jackson@company.com,2024-05-18,NaN,Denver
6,CUST_0053,Brian Williams,emily143.garcia@company.com,2024-09-10,326.45,Tucson
7,CUST_0125,Donna Gonzalez,david364.anderson@icloud.com,2024-11-07,100.88,Omaha
8,CUST_0069,Linda Allen,jessica844.gonzalez@outlook.com,09/12/2024,825.27,Louisville
9,CUST_0451,Paul Young,carol.hernandez@company.com,2023-04-06,66119.22,Miami

In [7]:
df.tail()

,Customer_ID,Full_Name,Email,Purchase_Date,Amount_Spent,City
495,CUST_0107,Andrew Young,karen777.davis@gmail.com,2023-06-01,404.32,Fort Worth
496,CUST_0271,Sarah Ramirez,emily736.white@gmail.com,2023-07-14,430.62,Phoenix
497,CUST_0349,Charles Anderson,anthony342.smith@hotmail.com,2023-09-12,382.53,NaN
498,CUST_0436,Andrew Miller,william596.lewis@gmail.com,2023-03-14,83.68,Albuquerque
499,CUST_0103,Donald Perez,linda.walker@gmail.com,2023-11-20,720.22,NaN

In [8]:
df.dtypes

Customer_ID      object
Full_Name        object
Email            object
Purchase_Date    object
Amount_Spent     object
City             object
dtype: object

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

Customer_ID      19
Full_Name        17
Email            29
Purchase_Date    27
Amount_Spent     22
City             29
dtype: int64

In [13]:
df[df['Customer_ID'].isnull()]

,Customer_ID,Full_Name,Email,Purchase_Date,Amount_Spent,City
15,NaN,Patricia Wright,brian.smith@icloud.com,2023-05-27,424.09,Philadelphia
20,NaN,Maria Wright,matthew929.clark@aol.com,2024-07-27,598.05,Portland
64,NaN,Elizabeth Perez,brian.sanchez@aol.com,1990-04-21,123.36,Mesa
87,NaN,Matthew Clark,david.lewis@gmail.com,2024-04-30,630.14,Austin
106,NaN,Donald Flores,maria711.jackson@icloud.com,2023-10-18,15.55,long beach
107,NaN,Joshua Martinez,not_an_email_229,2023-10-15,992.05,Nashville
155,NaN,Robert Walker,joshua946.martinez@outlook.com,2023-05-08,-330.37,Long Beach
156,NaN,William White,helen.williams@gmail.com,1990-06-10,"3,629.27",Omaha
160,NaN,Kenneth Lopez,lisa.rodriguez@gmail.com,2024-01-18,674.63,Baltimore
180,NaN,Maria Smith,sarah.martinez@company.com,2023-06-22,952.33,New York
246,NaN,Linda Clark,michael.nguyen@company.com,2024-05-04,662.1,Portland
294,NaN,Patricia Martin,james.walker@gmail.com,2023-02-14,595.26,San Jose
335,NaN,Nancy Scott,jessica.nguyen@company.com,2024-03-03,-437.88,Dallas
351,NaN,Paul Scott,emily.harris@gmail.com,2023-01-10,573.71,Oklahoma City
393,NaN,Lisa Sanchez,barbara.flores@icloud.com,2023-08-06,-197.47,Albuquerque
394,NaN,Donald Scott,karen.lee@company.com,2023-03-28,"4,381.93",Washington
455,NaN,Jessica Miller,maria.white@icloud.com,2023-01-29,485.66,Sacramento
456,NaN,Lisa Lopez,donna.lee@aol.com,1990-09-23,289.82,Virginia Beach
488,NaN,Mark Jones,sarah954.perez@yahoo.com,20-04-2024,31.08,NaN

In [15]:
df.describe().T

              count unique                      top freq
Customer_ID     481    470                CUST_0380    3
Full_Name       483    426            Sarah Ramirez    4
Email           471    462  paul.flores@hotmail.com    2
Purchase_Date   473    371               2023-04-02    5
Amount_Spent    478    478                   720.22    1
City            471     87              Minneapolis   16

In [18]:
len(df['City'].unique())

88

In [19]:
df['City'].unique()

array(['Charlotte', 'Chicago', nan, 'Baltimore', 'Las Vegas', 'Denver',
       'Tucson', 'Omaha', 'Louisville', 'Miami', 'Los Angeles',
       'Minneapolis', 'Indianapolis', 'Detroit', 'Philadelphia',
       'Nashville', 'Seattle', 'San Diego', 'Portland', 'New Orleans',
       'las vegas', 'Kansas City', 'New York', 'Austin', 'louisville',
       'San Francisco', 'Tulsa', 'San Francisco   ', 'Columbus',
       'Albuquerque', 'Boston', 'El Paso', 'Virginia Beach   ',
       'Sacramento', 'Phoenix', 'Colorado Springs', 'Fort Worth',
       'San Jose', 'Mesa', 'San Antonio', 'Fresno', 'Albuquerqe',
       'Virginia Beach', 'Dalas', 'Dallas', 'Long Beach', 'SAN JOSE',
       'Oakland', 'long beach', 'Arlington', 'Houston', 'Jacksonville',
       'Atlanta', 'new york', 'fresno', 'virginia beach', 'Milwaukee',
       'Raleigh', 'Indinapolis', 'Washington', 'Chicago   ',
       'Oklahoma City', 'Minneapolis   ', 'minneapolis', 'Kansas City   ',
       'Omaha   ', 'Denvr', 'sacramento', 'CHARLOTTE', 'nashville',
       'Phoenix   ', 'Albuquerque   ', 'SAN DIEGO', 'omaha', 'San Anonio',
       'Colorado Springs   ', 'dallas', 'tucson', 'Atlanta   ',
       'Austin   ', 'san francisco', 'Seattle   ', 'Scramento', 'RALEIGH',
       'SanAntonio', 'Boston   ', 'Oakand', 'Ls Angeles'], dtype=object)

In [23]:
df['Customer_ID'].duplicated().sum()

np.int64(11)

In [26]:
df[df['Customer_ID'].duplicated(keep=False)].sort_values(by='Customer_ID')

,Customer_ID,Full_Name,Email,Purchase_Date,Amount_Spent,City
135,CUST_0058,thomas sanchez,NaN,2024-07-27,702.75,San Diego
367,CUST_0058,Sandra Moore,jennifer.jackson@outlook.com,2024-11-11,630.36,fresno
494,CUST_0072,BARBARA WALKER,charles420.wilson@company.com,2023-05-05,46.12,Minneapolis
174,CUST_0072,James Young,helen.king@company.com,2023-03-14,-236.27,Raleigh
211,CUST_0120,Helen Harris,nancy.lewis@outlook.com,2024-09-20,814.16,San Antonio
230,CUST_0120,Helen Hill,andrew.torres@yahoo.com,2024-11-06,59.16,NaN
134,CUST_0126,Lisa Robinson,donald.clark@aol.com,2024-08-28,30.62,new york
279,CUST_0126,Maria Jones,david.williams@outlook.com,2023-01-17,857.3,Dallas
438,CUST_0288,Lisa Jackson,linda.lewis@hotmail.com,2023-10-16,NaN,Mesa
260,CUST_0288,Steven Torres,donna831.thomas@hotmail.com,2026-05-10,951.94,Milwaukee
322,CUST_0303,Brian Wilson,sarah.perez@company.com,2023-07-30,754.16,Washington
280,CUST_0303,Kevin Lee,kenneth536.wilson@icloud.com,2023-01-12,598.51,Raleigh
478,CUST_0309,Sandra Jackson,jane543.williams@hotmail.com,2024-04-12,87.01 USD,Raleigh
306,CUST_0309,Barbara Torres,betty.garcia@hotmail.com,2024-08-15,824.17,El Paso
482,CUST_0360,Steven White,lisa.smith@gmail.com,2024-03-10,120.56,Portland
104,CUST_0360,Emily Miller,william.harris@gmail.com,2023-04-15,445.2,Nashville
430,CUST_0367,Barbara Wilson,paul.flores@hotmail.com,2023-04-02,134.79,Long Beach
28,CUST_0367,Barbara Garcia,daniel.king@hotmail.com,2023-09-27,810.92,New Orleans
331,CUST_0380,John Davis,james109.nguyen@yahoo.com,2024-08-06,794.48,Nashville
235,CUST_0380,Jessica!!! Thomas??,nancy.davis@yahoo.com,2023-04-04,777.85,Houston
390,CUST_0380,John Wilson,linda814.lee@aol.com,2023-04-13,92.26,Portland

#

# Cleaning

In [27]:
df.dropna(subset='Customer_ID',inplace=True)

In [29]:
df.drop_duplicates(subset='Customer_ID',keep='first',inplace=True)

In [30]:
df['Full_Name']=df['Full_Name'].fillna('Unknown')

In [31]:
df['Full_Name']=df['Full_Name'].str.strip().str.title()

In [33]:
mask = df['Email'].str.contains(
    r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$',
    regex=True,
    na=False
)

In [34]:
df.loc[~mask, 'Email'] = np.nan

In [35]:
df['Purchase_Date'].unique()[:23]

array([nan, '2023-11-01', '09/30/2023', '2024-07-29', '2023-09-24',
       '2024-05-18', '2024-09-10', '2024-11-07', '09/12/2024',
       '2023-04-06', '2023-11-05', '2024-07-07', '2023-02-23',
       '2023-04-02', '2023-07-16', '2023-07-31', '1990-02-23',
       '2024-04-29', '2023-03-11', '06/08/2024', '2024-01-18',
       '2023-04-13', '2023-02-28'], dtype=object)

In [36]:
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'],format = 'mixed',yearfirst=True,errors='coerce')

In [38]:
df['Purchase_Date'].isnull().sum()

np.int64(27)

In [39]:
df['Amount_Spent'].unique()[:20]

array(['470.12', '313.9', '-111.5', '-182.61', '389.22', nan, '326.45',
       '100.88', '825.27', '66119.22', '752.94', '135.92', '676.55',
       '619.43', '613.94', '555.99', '2,456.65', '976.69', '34.0',
       '511.9'], dtype=object)

In [40]:
df['Amount_Spent'] = pd.to_numeric(df['Amount_Spent'],errors='coerce')

In [42]:
df.loc[df['Amount_Spent']<0,'Amount_Spent'] = np.nan

In [43]:
len(df['City'].unique())

88

In [44]:
len(df['City'].str.strip().str.title().unique())

58

In [45]:
df['City'].str.strip().str.title().unique()

array(['Charlotte', 'Chicago', nan, 'Baltimore', 'Las Vegas', 'Denver',
       'Tucson', 'Omaha', 'Louisville', 'Miami', 'Los Angeles',
       'Minneapolis', 'Indianapolis', 'Detroit', 'Philadelphia',
       'Nashville', 'Seattle', 'San Diego', 'New Orleans', 'Kansas City',
       'New York', 'Austin', 'San Francisco', 'Tulsa', 'Columbus',
       'Albuquerque', 'Boston', 'El Paso', 'Virginia Beach', 'Sacramento',
       'Phoenix', 'Colorado Springs', 'Fort Worth', 'San Jose',
       'San Antonio', 'Fresno', 'Albuquerqe', 'Dalas', 'Dallas',
       'Long Beach', 'Mesa', 'Oakland', 'Arlington', 'Houston',
       'Portland', 'Jacksonville', 'Atlanta', 'Milwaukee', 'Raleigh',
       'Indinapolis', 'Washington', 'Oklahoma City', 'Denvr',
       'San Anonio', 'Scramento', 'Sanantonio', 'Oakand', 'Ls Angeles'],
      dtype=object)

In [46]:
city_map = {
    'Albuquerqe': 'Albuquerque',
    'Dalas': 'Dallas',
    'Indinapolis': 'Indianapolis',
    'Denvr': 'Denver',
    'San Anonio': 'San Antonio',
    'Sanantonio': 'San Antonio',
    'Scramento': 'Sacramento',
    'Oakand': 'Oakland',
    'Ls Angeles': 'Los Angeles'
}

In [47]:
df['City'] = df['City'].replace(city_map)

In [48]:
df['Amount_Spent'] = df['Amount_Spent'].fillna(df.groupby('City')['Amount_Spent'].transform(lambda a : a.median()))

In [49]:
df['City'].isnull().sum()

np.int64(27)

In [50]:
df.isnull().sum()

Customer_ID       0
Full_Name         0
Email            59
Purchase_Date    27
Amount_Spent      7
City             27
dtype: int64

In [51]:
df['City'] = df['City'].fillna('Unknown')

In [54]:
df['Purchase_Date'] = df['Amount_Spent'].fillna(df.groupby('City')['Purchase_Date'].transform(lambda a : a.mode()[0] if not a.mode().empty else np.nan))

In [55]:
df.isnull().sum()

Customer_ID       0
Full_Name         0
Email            59
Purchase_Date     0
Amount_Spent      7
City              0
dtype: int64

In [56]:
df['Email'] = df['Email'].fillna('not available')

In [58]:
df.dropna(subset='Amount_Spent',inplace=True)

In [59]:
df.isnull().sum()

Customer_ID      0
Full_Name        0
Email            0
Purchase_Date    0
Amount_Spent     0
City             0
dtype: int64

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 463 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    463 non-null    object
 1   Full_Name      463 non-null    object
 2   Email          463 non-null    object
 3   Purchase_Date  463 non-null    object
 4   Amount_Spent   463 non-null    float64
 5   City           463 non-null    object
dtypes: float64(1), object(5)
memory usage: 25.3+ KB