# Data Cleaning Practice 4

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = pd.read_csv('messy_data3_ecommerce.csv')

In [4]:
df = data.copy(deep=True)

#

## #Data Inspection

In [5]:
df.head()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
0,ORD10006,Nitara Bumb,NaN,NaN,5.0,NaN,110.0,Delhi,UPI,2023-06-01,-1.0,shray@gmail
1,ORD10001,Kanav,Laptop,NaN,NaN,18817,NaN,Bangalore,UPI,2025-04-16,8.0,nehmat90@gmail.com
2,ORD10037,NaN,Tablet,NaN,0.0,NaN,110.0,Bangalore,NetBanking,NaN,NaN,NaN
3,NaN,NaN,Tablet,Electronics,3.0,unknown,110.0,Delhi,NaN,45-14-2024,NaN,NaN
4,ORD10073,Aayush Deep,Phone,Electronics,6.0,-5000,25.0,NaN,Cash,45-14-2024,NaN,wrong_email

In [6]:
df.tail()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
995,ORD10047,NaN,Phone,NaN,0.0,NaN,NaN,Delhi,Card,2023-11-26,2.0,NaN
996,NaN,NaN,Monitor,Electronics,NaN,110487,4.0,Mumbai,NaN,NaN,2.0,wrong_email
997,ORD10997,NaN,Mouse,Electronics,NaN,NaN,-10.0,Bangalore,UPI,NaN,-1.0,wrong_email
998,ORD10998,Romil Venkatesh,Tablet,Electronics,-2.0,-5000,18.0,Pune,Card,NaN,-1.0,yakshit14@gmail.com
999,ORD10019,NaN,Keyboard,Electronics,10.0,104048,110.0,NaN,NaN,45-14-2024,8.0,NaN

In [7]:
df.sample(10)

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
463,NaN,NaN,Monitor,Office,5.0,-5000,110.0,Mumbai,NetBanking,45-14-2024,NaN,jkrish@khatri-bora.net
188,NaN,NaN,Keyboard,NaN,0.0,NaN,NaN,NaN,Cash,2025-12-27,NaN,onkar91@swaminathan.com
250,ORD10250,NaN,Tablet,Accessories,0.0,unknown,110.0,Delhi,NaN,2025-06-02,8.0,navya@gmail
799,NaN,Heer,Mouse,NaN,-2.0,unknown,110.0,Bangalore,Cash,2024-06-16,4.0,NaN
232,ORD10097,Sara Gara,Phone,Electronics,-2.0,NaN,110.0,Delhi,NetBanking,NaN,-1.0,waliprisha@hotmail.com
975,NaN,NaN,Monitor,Electronics,NaN,37166,44.0,Delhi,UPI,2025-07-12,NaN,indrajit@gmail
707,ORD10707,NaN,Tablet,Electronics,NaN,unknown,46.0,Pune,NaN,NaN,-1.0,wrong_email
333,ORD10333,NaN,Laptop,Accessories,9.0,-5000,49.0,Bangalore,UPI,NaN,8.0,NaN
488,NaN,Hansh Dutta,Monitor,Electronics,9.0,-5000,-10.0,Pune,NaN,2024-11-06,NaN,shamik@gmail
605,ORD10077,NaN,Laptop,Accessories,NaN,unknown,2.0,Hyderabad,Card,2026-05-02,NaN,kiaan48@sood.com

In [8]:
df.shape

(1000, 12)

In [9]:
df.isnull().sum()

Order_ID            331
Customer_Name       498
Product             161
Category            245
Quantity            242
Price               251
Discount_Percent    260
City                176
Payment_Method      349
Order_Date          323
Customer_Rating     239
Email               258
dtype: int64

In [10]:
df.isnull().mean()*100

Order_ID            33.1
Customer_Name       49.8
Product             16.1
Category            24.5
Quantity            24.2
Price               25.1
Discount_Percent    26.0
City                17.6
Payment_Method      34.9
Order_Date          32.3
Customer_Rating     23.9
Email               25.8
dtype: float64

In [11]:
df.isnull().mean().mean()*100

np.float64(27.775)

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df['Order_ID'].duplicated().sum()

np.int64(584)

In [24]:
df[df['Order_ID'].duplicated() == True].head()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
5,NaN,NaN,Monitor,NaN,1.0,NaN,12.0,Delhi,Cash,NaN,NaN,NaN
6,ORD10006,Jhanvi Ray,Keyboard,Office,2.0,114060,NaN,Bangalore,NaN,NaN,4.0,aarush@gmail
8,NaN,Siya Khare,NaN,NaN,0.0,unknown,NaN,Delhi,Card,NaN,3.0,wrong_email
9,NaN,NaN,Monitor,Electronics,NaN,unknown,NaN,Delhi,NetBanking,2023-05-28,-1.0,wrong_email
10,NaN,Ranbir Raja,Keyboard,Office,0.0,unknown,-10.0,Mumbai,Cash,45-14-2024,4.0,vedikachandra@gopal.org

In [29]:
df[df['Order_ID'].duplicated(keep=False)].sort_values('Order_ID').head()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
610,ORD10000,NaN,Monitor,Electronics,0.0,-5000,110.0,NaN,Cash,2026-04-13,8.0,kashvi@gmail
276,ORD10000,NaN,Monitor,Electronics,0.0,NaN,0.0,Mumbai,Card,45-14-2024,8.0,NaN
461,ORD10000,NaN,Tablet,NaN,0.0,unknown,NaN,Mumbai,Card,45-14-2024,8.0,rati@gmail
587,ORD10000,Purab Chauhan,NaN,Accessories,-2.0,-5000,-10.0,Bangalore,NetBanking,NaN,-1.0,NaN
1,ORD10001,Kanav,Laptop,NaN,NaN,18817,NaN,Bangalore,UPI,2025-04-16,8.0,nehmat90@gmail.com

In [33]:
df.describe().T

                  count       mean        std   min   25%   50%    75%    max
Quantity          758.0   1.120053   3.507696  -2.0  -2.0   0.0    3.0   10.0
Discount_Percent  740.0  43.745946  51.460434 -10.0 -10.0  28.5  110.0  110.0
Customer_Rating   761.0   3.534823   3.760131  -1.0  -1.0   4.0    8.0    8.0

In [32]:
df.describe(include='object').T

               count unique          top freq
Order_ID         669    415     ORD10023    7
Customer_Name    502    414         Anay    5
Product          839      6       Laptop  144
Category         755      3  Electronics  262
Price            749    242      unknown  261
City             824      5        Delhi  193
Payment_Method   651      4   NetBanking  177
Order_Date       677    302   45-14-2024  339
Email            742    379  wrong_email  253

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          669 non-null    object
 1   Customer_Name     502 non-null    object
 2   Product           839 non-null    object
 3   Category          755 non-null    object
 4   Quantity          758 non-null    float64
 5   Price             749 non-null    object
 6   Discount_Percent  740 non-null    float64
 7   City              824 non-null    object
 8   Payment_Method    651 non-null    object
 9   Order_Date        677 non-null    object
 10  Customer_Rating   761 non-null    float64
 11  Email             742 non-null    object
dtypes: float64(3), object(9)
memory usage: 93.9+ KB

#

## #Data Cleaning

In [35]:
df['Order_ID'].duplicated().mean()*100

np.float64(58.4)

In [39]:
df.shape[0]

1000

In [40]:
df.drop_duplicates(subset='Order_ID').shape[0]

416

In [42]:
df.drop_duplicates(subset='Order_ID',keep="first").shape[0]

416

In [43]:
df.drop_duplicates(subset='Order_ID',keep=False).shape[0]

316

In [47]:
df.dropna(subset='Order_ID').shape

(669, 12)

In [48]:
df = df.dropna(subset='Order_ID')

In [49]:
df.shape

(669, 12)

In [52]:
df['Order_ID'].isnull().sum()

np.int64(0)

#

In [53]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Product', 'Category', 'Quantity', 'Price',
       'Discount_Percent', 'City', 'Payment_Method', 'Order_Date',
       'Customer_Rating', 'Email'],
      dtype='object')

In [54]:
df['Customer_Name'].nunique()

297

In [57]:
df[df['Customer_Name'] ==' ']

Empty DataFrame
Columns: [Order_ID, Customer_Name, Product, Category, Quantity, Price, Discount_Percent, City, Payment_Method, Order_Date, Customer_Rating, Email]
Index: []

In [58]:
df[df['Customer_Name'].isnull()]

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
2,ORD10037,NaN,Tablet,NaN,0.0,NaN,110.0,Bangalore,NetBanking,NaN,NaN,NaN
12,ORD10100,NaN,Mouse,NaN,0.0,unknown,-10.0,Pune,Card,NaN,NaN,eva@gmail
14,ORD10014,NaN,Monitor,Office,NaN,97104,18.0,Delhi,NaN,NaN,3.0,NaN
17,ORD10017,NaN,Keyboard,Office,10.0,NaN,14.0,Delhi,Cash,2023-08-03,-1.0,NaN
19,ORD10013,NaN,NaN,Accessories,9.0,NaN,NaN,Bangalore,UPI,NaN,NaN,amira@gmail
...,...,...,...,...,...,...,...,...,...,...,...,...
981,ORD10981,NaN,Phone,Office,1.0,unknown,13.0,NaN,UPI,2026-03-17,-1.0,madanbhamini@yahoo.com
983,ORD10101,NaN,Monitor,Electronics,-2.0,unknown,-10.0,Delhi,NaN,2026-03-30,NaN,NaN
995,ORD10047,NaN,Phone,NaN,0.0,NaN,NaN,Delhi,Card,2023-11-26,2.0,NaN
997,ORD10997,NaN,Mouse,Electronics,NaN,NaN,-10.0,Bangalore,UPI,NaN,-1.0,wrong_email
999,ORD10019,NaN,Keyboard,Electronics,10.0,104048,110.0,NaN,NaN,45-14-2024,8.0,NaN

In [59]:
df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_16448\3949358649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')

In [60]:
df[df['Customer_Name'].isnull()]

Empty DataFrame
Columns: [Order_ID, Customer_Name, Product, Category, Quantity, Price, Discount_Percent, City, Payment_Method, Order_Date, Customer_Rating, Email]
Index: []

#

In [61]:
df['Order_ID'] = df['Order_ID'].str.strip().str.upper()

C:\Users\Omkar Yallurkar\AppData\Local\Temp\ipykernel_16448\3292853389.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_ID'] = df['Order_ID'].str.strip().str.upper()

In [62]:
df.loc[:, 'Customer_Name'] = df['Customer_Name'].str.strip().str.upper()

In [65]:
ob_col = df.select_dtypes(include='object').columns

In [66]:
ob_col

Index(['Order_ID', 'Customer_Name', 'Product', 'Category', 'Price', 'City',
       'Payment_Method', 'Order_Date', 'Email'],
      dtype='object')

In [69]:
for col in ['Customer_Name', 'Product', 'Category','Payment_Method', 'City']:
    df.loc[:,col] = df[col].str.strip().str.upper()

#

### Datatype Formatting

In [70]:
df.dtypes

Order_ID             object
Customer_Name        object
Product              object
Category             object
Quantity            float64
Price                object
Discount_Percent    float64
City                 object
Payment_Method       object
Order_Date           object
Customer_Rating     float64
Email                object
dtype: object

In [71]:
df['Quantity'].unique()

array([ 5., nan,  0.,  6.,  2., 10.,  9.,  4., -2.,  3.,  7.,  8.,  1.])

In [74]:
df.loc[:, 'Quantity'] = df['Quantity'].astype('Int64')

In [75]:
df['Quantity'].dtypes

Int64Dtype()

In [76]:
df['Quantity'].unique()

<IntegerArray>
[5, <NA>, 0, 6, 2, 10, 9, 4, -2, 3, 7, 8, 1]
Length: 13, dtype: Int64

In [77]:
df['Price'].unique()

array([nan, '18817', '-5000', '114060', 'unknown', '97104', '102758',
       '43115', '70260', '130915', '67912', '85902', '43417', '82970',
       '8300', '129906', '71974', '27357', '16755', '71789', '120068',
       '72217', '128431', '24921', '75027', '31263', '66704', '119617',
       '36593', '115448', '52996', '19984', '121317', '126053', '75143',
       '17529', '3240', '37484', '112328', '50423', '12550', '125998',
       '60533', '103759', '83067', '134714', '51004', '147482', '40822',
       '72291', '87453', '75071', '98474', '129949', '95756', '54760',
       '70895', '103461', '93167', '109746', '85843', '106301', '34636',
       '16622', '110031', '121898', '89612', '54629', '62668', '131571',
       '2630', '73153', '14251', '23685', '125010', '54153', '122780',
       '79579', '57906', '125051', '86812', '92940', '89044', '37153',
       '61732', '132547', '90589', '111356', '30629', '27842', '46012',
       '103720', '143274', '140599', '61118', '37518', '11009', '2363',
       '122951', '103099', '9387', '131830', '50910', '63399', '117387',
       '77026', '131772', '68739', '66750', '77473', '69256', '54756',
       '110676', '32830', '20906', '18659', '18445', '24940', '139105',
       '85405', '59891', '119197', '11697', '126161', '62160', '32786',
       '23078', '3653', '25538', '52383', '30665', '38635', '39648',
       '149117', '77787', '124865', '135986', '95469', '133535', '94899',
       '130694', '57930', '89095', '77166', '51533', '23774', '48170',
       '32624', '142390', '49826', '49116', '109431', '93403', '14047',
       '35773', '51897', '69577', '97152', '119944', '74170', '104918',
       '80687', '104048'], dtype=object)

In [78]:
df.loc[:, 'Price'] = pd.to_numeric('Price',errors='coerce')

In [82]:
df['Price'].dtypes.name

'object'

In [84]:
df.loc[:, 'Price'] = pd.to_numeric(df['Price'], errors='coerce')

In [85]:
df['Price'].dtypes.name

'float64'

In [88]:
df['Price'].unique()

array([nan])

In [91]:
df.loc[:, 'Price'] = pd.to_numeric(data['Price'], errors='coerce')

In [94]:
df['Price'].unique()[:5]

array([nan, 18817.0, -5000.0, 114060.0, 97104.0], dtype=object)

In [95]:
df['Order_Date'].unique()[:10]

array(['2023-06-01', '2025-04-16', nan, '45-14-2024', '2025-08-13',
       '2025-04-05', '2023-08-03', '2024-02-10', '2026-02-08',
       '2026-03-15'], dtype=object)

In [96]:
df['Order_Date'].unique()[-10:]

array(['2023-09-08', '2025-07-11', '2024-08-27', '2025-06-15',
       '2025-03-23', '2025-06-11', '2024-08-03', '2026-03-17',
       '2026-03-30', '2023-11-26'], dtype=object)

In [98]:
df['Order_Date'].sample(20)

53     2024-02-02
618           NaN
869           NaN
862           NaN
662    45-14-2024
541    45-14-2024
244    45-14-2024
965    2025-06-11
960    2025-06-15
28            NaN
412    2025-08-18
180    2023-09-02
951           NaN
810    2024-11-03
733    45-14-2024
963    2025-03-23
686    2023-06-04
716    45-14-2024
511    45-14-2024
789           NaN
Name: Order_Date, dtype: object

In [99]:
df.loc[:,'Order_Date'] = pd.to_datetime(df['Order_Date'],errors='coerce')

In [100]:
df['Order_Date'].sample(20)

652    2023-11-03 00:00:00
709    2023-12-22 00:00:00
355                    NaT
413                    NaT
871                    NaT
744                    NaT
519    2025-10-30 00:00:00
54     2024-03-22 00:00:00
688    2025-02-18 00:00:00
196    2024-06-15 00:00:00
954                    NaT
798                    NaT
158    2024-11-26 00:00:00
205                    NaT
484    2023-08-27 00:00:00
486    2025-11-16 00:00:00
940                    NaT
959    2024-08-27 00:00:00
481                    NaT
991                    NaT
Name: Order_Date, dtype: object

#

#

### Handle Invalid Values

In [101]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Product', 'Category', 'Quantity', 'Price',
       'Discount_Percent', 'City', 'Payment_Method', 'Order_Date',
       'Customer_Rating', 'Email'],
      dtype='object')

In [106]:
for col in ['Product', 'Category','Payment_Method']:
    print(df[col].unique())
    print()

[nan 'LAPTOP' 'TABLET' 'PHONE' 'KEYBOARD' 'MOUSE' 'MONITOR']

[nan 'ELECTRONICS' 'OFFICE' 'ACCESSORIES']

['UPI' 'NETBANKING' 'CASH' nan 'CARD']

In [107]:
df['City'].unique()

array(['DELHI', 'BANGALORE', nan, 'PUNE', 'HYDERABAD', 'MUMBAI'],
      dtype=object)

In [108]:
df.describe().T

                  count       mean        std   min   25%   50%    75%    max
Quantity          508.0   1.124016   3.437577  -2.0  -2.0   0.0    3.0   10.0
Discount_Percent  493.0  44.231237  51.197879 -10.0 -10.0  29.0  110.0  110.0
Customer_Rating   512.0   3.681641   3.722547  -1.0  -1.0   4.0    8.0    8.0

In [111]:
df.loc[df['Discount_Percent'] < 0, 'Discount_Percent'] = np.nan

In [112]:
df.loc[(df['Discount_Percent']  < 0) |(df['Discount_Percent']  > 85),'Discount_Percent' ] = np.nan

In [113]:
df.loc[(df['Customer_Rating'] < 1) |(df['Customer_Rating'] > 5),'Customer_Rating'] = np.nan

In [114]:
df.describe().T

                  count       mean        std  min   25%   50%   75%   max
Quantity          508.0   1.124016   3.437577 -2.0  -2.0   0.0   3.0  10.0
Discount_Percent  169.0  25.360947  14.850642  0.0  13.0  25.0  39.0  50.0
Customer_Rating   180.0   3.166667   1.408276  1.0   2.0   3.0   4.0   5.0

#

### Data Validation

In [116]:
import re

In [117]:
pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'

In [118]:
valid_email = df['Email'].str.match(pattern,na=False)

In [119]:
df.loc[~valid_email, 'Email'] = pd.NA

In [120]:
df.shape

(669, 12)

#

In [125]:
mode_values = df.groupby('Order_ID').agg({
    'City': lambda x: x.mode().iloc[0] if not x.mode().empty else pd.NA,
    'Order_Date': lambda x: x.mode().iloc[0] if not x.mode().empty else pd.NA
}).reset_index()

In [126]:
mode_values

     Order_ID       City           Order_Date
0    ORD10000     MUMBAI  2026-04-13 00:00:00
1    ORD10001  BANGALORE  2023-09-15 00:00:00
2    ORD10002  HYDERABAD                 <NA>
3    ORD10003       PUNE  2023-12-31 00:00:00
4    ORD10004      DELHI  2024-09-24 00:00:00
..        ...        ...                  ...
410  ORD10981       <NA>  2026-03-17 00:00:00
411  ORD10985       <NA>                 <NA>
412  ORD10992       PUNE                 <NA>
413  ORD10997  BANGALORE                 <NA>
414  ORD10998       PUNE                 <NA>

[415 rows x 3 columns]

In [127]:
mode_values.rename(columns={
    'City': 'Valid_City',
    'Order_Date': 'Valid_Date'
}, inplace=True)

In [128]:
df = df.merge(mode_values, on='Order_ID')

In [129]:
df.head()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email,Valid_City,Valid_Date
0,ORD10006,NITARA BUMB,NaN,NaN,5,NaN,NaN,DELHI,UPI,2023-06-01 00:00:00,NaN,<NA>,DELHI,2023-06-01 00:00:00
1,ORD10001,KANAV,LAPTOP,NaN,<NA>,18817.0,NaN,BANGALORE,UPI,2025-04-16 00:00:00,NaN,nehmat90@gmail.com,BANGALORE,2023-09-15 00:00:00
2,ORD10037,UNKNOWN,TABLET,NaN,0,NaN,NaN,BANGALORE,NETBANKING,NaT,NaN,<NA>,BANGALORE,2023-09-05 00:00:00
3,ORD10073,AAYUSH DEEP,PHONE,ELECTRONICS,6,-5000.0,25.0,NaN,CASH,NaT,NaN,<NA>,MUMBAI,<NA>
4,ORD10006,JHANVI RAY,KEYBOARD,OFFICE,2,114060.0,NaN,BANGALORE,NaN,NaT,4.0,<NA>,DELHI,2023-06-01 00:00:00

In [130]:
df = df[(df['City'] == df['Valid_City']) &(df['Order_Date'] == df['Valid_Date'])]

In [131]:
df.drop(columns=['Valid_City', 'Valid_Date'], inplace=True)

In [132]:
df.head()

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Discount_Percent,City,Payment_Method,Order_Date,Customer_Rating,Email
0,ORD10006,NITARA BUMB,NaN,NaN,5,NaN,NaN,DELHI,UPI,2023-06-01 00:00:00,NaN,<NA>
16,ORD10084,JAYANT CHEEMA,LAPTOP,ACCESSORIES,<NA>,-5000.0,42.0,DELHI,NETBANKING,2026-03-15 00:00:00,NaN,<NA>
26,ORD10035,UNKNOWN,PHONE,ELECTRONICS,<NA>,NaN,NaN,HYDERABAD,NaN,2024-04-08 00:00:00,NaN,<NA>
29,ORD10014,EMIR VAIDYA,TABLET,NaN,-2,67912.0,44.0,DELHI,CARD,2024-06-17 00:00:00,1.0,<NA>
34,ORD10054,MIRAAN,NaN,OFFICE,-2,85902.0,NaN,BANGALORE,CASH,2024-03-22 00:00:00,NaN,<NA>

In [133]:
df.shape

(106, 12)

In [134]:
df['Order_ID'].duplicated().sum()

np.int64(0)

In [136]:
# wrong data cleaning