# Bernoulli Distribution Analysis

##### A Bernoulli distribution is a probability distribution that describes a single experiment with only two possible outcomes:
- Success
- Failure

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
df = pd.read_excel('bernoulli_dummy_data.xlsx')

In [4]:
df.head()

   Customer_ID  Age  Gender       City  Visited  Purchased
0            1   30  Female  Bangalore        8          1
1            2   25    Male     Mumbai        6          0
2            3   18  Female      Delhi        9          1
3            4   45    Male  Bangalore       10          1
4            5   41    Male     Mumbai       10          1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  100 non-null    int64
 1   Age          100 non-null    int64
 2   Gender       100 non-null    object
 3   City         100 non-null    object
 4   Visited      100 non-null    int64
 5   Purchased    100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [6]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe().T

             count   mean        std   min    25%   50%    75%    max
Customer_ID  100.0  50.50  29.011492   1.0  25.75  50.5  75.25  100.0
Age          100.0  37.68  13.165520  18.0  26.00  38.5  49.00   60.0
Visited      100.0   5.70   2.858622   1.0   3.00   6.0   8.00   10.0
Purchased    100.0   0.53   0.501614   0.0   0.00   1.0   1.00    1.0

#

In [20]:
df['Gender'].nunique() == 2

True

In [21]:
df["Gender_Binary"] = df["Gender"].map({"Male": 1, "Female": 0})

In [22]:
df.head()

   Customer_ID  Age  Gender       City  Visited  Purchased  Gender_Binary
0            1   30  Female  Bangalore        8          1              0
1            2   25    Male     Mumbai        6          0              1
2            3   18  Female      Delhi        9          1              0
3            4   45    Male  Bangalore       10          1              1
4            5   41    Male     Mumbai       10          1              1

#### Gender

#### Q1. What is the probability that a randomly selected customer is Male?

In [33]:
p = (df["Gender"] == "Male").mean()

In [34]:
print(stats.bernoulli.pmf(1, p))

0.53

###### Another Way

In [37]:
p1 = (df['Gender_Binary']==1).mean()

In [38]:
print(stats.bernoulli.pmf(1, p1))

0.53

#

#### Q2. What is the probability that a randomly selected customer is Female?

In [40]:
print(stats.bernoulli.pmf(0,p))

0.4700000000000002

In [41]:
print(stats.bernoulli.pmf(0, p1))

0.4700000000000002

#

#### Q3. Does Gender follow a Bernoulli distribution?

In [43]:
df["Gender"].nunique() == 2

True

#

#### Q4. Expected Male customers in next 100 customers?

In [46]:
print(100 * p)

53.0

#

#### Q5.What is the variance of the Gender distribution?

In [49]:
print(stats.bernoulli.var(p))

0.2491

#

## Purchased  column

#### Q1. Probability customer purchases?

In [54]:
p3 = df["Purchased"].mean()

In [56]:
print(stats.bernoulli.pmf(1,p3))

0.53

#### Q2. Probability customer does not purchase?

In [57]:
print(stats.bernoulli.pmf(0,p3))

0.4700000000000002

#

#### Q3. Does Purchased follow Bernoulli distribution?

In [66]:
print(set(df["Purchased"].unique()).issubset({0,1}))

True

#

#### Q4. Expected purchases in next 100 customers?

In [71]:
print(100*p3)

53.0

####

#### Q5. Variance of purchase outcome?

In [73]:
print(stats.bernoulli.var(p))

0.2491